In [2]:
#from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

/home/roger22/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "


In [3]:
#List of the symptoms is listed here in list l1.
l1=['back_pain','constipation','abdominal_pain','diarrhoea','mild_fever','yellow_urine',
    'yellowing_of_eyes','acute_liver_failure','fluid_overload','swelling_of_stomach',
    'swelled_lymph_nodes','malaise','blurred_and_distorted_vision','phlegm','throat_irritation',
    'redness_of_eyes','sinus_pressure','runny_nose','congestion','chest_pain','weakness_in_limbs',
    'fast_heart_rate','pain_during_bowel_movements','pain_in_anal_region','bloody_stool',
    'irritation_in_anus','neck_pain','dizziness','cramps','bruising','obesity','swollen_legs',
    'swollen_blood_vessels','puffy_face_and_eyes','enlarged_thyroid','brittle_nails',
    'swollen_extremeties','excessive_hunger','extra_marital_contacts','drying_and_tingling_lips',
    'slurred_speech','knee_pain','hip_joint_pain','muscle_weakness','stiff_neck','swelling_joints',
    'movement_stiffness','spinning_movements','loss_of_balance','unsteadiness',
    'weakness_of_one_body_side','loss_of_smell','bladder_discomfort','foul_smell_of urine',
    'continuous_feel_of_urine','passage_of_gases','internal_itching','toxic_look_(typhos)',
    'depression','irritability','muscle_pain','altered_sensorium','red_spots_over_body','belly_pain',
    'abnormal_menstruation','dischromic _patches','watering_from_eyes','increased_appetite','polyuria','family_history','mucoid_sputum',
    'rusty_sputum','lack_of_concentration','visual_disturbances','receiving_blood_transfusion',
    'receiving_unsterile_injections','coma','stomach_bleeding','distention_of_abdomen',
    'history_of_alcohol_consumption','fluid_overload','blood_in_sputum','prominent_veins_on_calf',
    'palpitations','painful_walking','pus_filled_pimples','blackheads','scurring','skin_peeling',
    'silver_like_dusting','small_dents_in_nails','inflammatory_nails','blister','red_sore_around_nose',
    'yellow_crust_ooze']
# Total number of symptoms
print(len(l1))

#List of Diseases is listed in list disease.
disease=['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo']
# Total number of diseases
print(len(disease))

95
41


In [4]:
l2=[]
for i in range(0,len(l1)):
    l2.append(0)
print(l2)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [7]:
import os
print(os.getcwd())
os.chdir("/mnt/d/Codes/MiniProject/model_repo/")
print(os.getcwd())

/mnt/d/WslFiles
/mnt/d/Codes/MiniProject/model_repo


In [10]:
#Reading the training .csv file
df = pd.read_excel("datasets//training.xlsx")
dff = pd.read_excel("datasets//training.xlsx", index_col='prognosis')

df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [11]:
print("df: ",df.shape)
print("dff: ",dff.shape)

df:  (4920, 133)
dff:  (4920, 132)


In [12]:
print("df : ",df.columns)
print("dff : ", dff.columns)

df :  Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)
dff :  Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'pus_filled_pimples', 'blackheads', 'scurring', 'skin_peeling',
       'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails',
       'blister', 'red_sore_around_nose', 'yellow_crust_ooze'],
      dtype='object', length=132)


In [13]:
#Label encoding the disease column
df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)

/tmp/ipykernel_27800/1475562587.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,


In [14]:
dff.head()

itching  skin_rash  nodal_skin_eruptions  \
prognosis                                                    
Fungal infection        1          1                     1   
Fungal infection        0          1                     1   
Fungal infection        1          0                     1   
Fungal infection        1          1                     0   
Fungal infection        1          1                     1   

                  continuous_sneezing  shivering  chills  joint_pain  \
prognosis                                                              
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   

                  stomach_pain  acidity  ulcers_on_tongue  ...  \
prognosis                                                  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   

                  pus_filled_pimples  blackheads  scurring  skin_peeling  \
prognosis                                                                  
Fungal infection                   0           0         0             0   
Fungal infection                   0           0         0             0   
Fungal infection                   0           0         0             0   
Fungal infection                   0           0         0             0   
Fungal infection                   0           0         0             0   

                  silver_like_dusting  small_dents_in_nails  \
prognosis                                                     
Fungal infection                    0                     0   
Fungal infection                    0                     0   
Fungal infection                    0                     0   
Fungal infection                    0                     0   
Fungal infection                    0                     0   

                  inflammatory_nails  blister  red_sore_around_nose  \
prognosis                                                             
Fungal infection                   0        0                     0   
Fungal infection                   0        0                     0   
Fungal infection                   0        0                     0   
Fungal infection                   0        0                     0   
Fungal infection                   0        0                     0   

                  yellow_crust_ooze  
prognosis                            
Fungal infection                  0  
Fungal infection                  0  
Fungal infection                  0  
Fungal infection                  0  
Fungal infection                  0  

[5 rows x 132 columns]

In [15]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze  prognosis  
0                  0          0  
1                  0          0  
2                  0          0  
3                  0          0  
4                  0          0  

[5 rows x 133 columns]

In [20]:
df.shape

(4920, 133)

In [17]:
x= df[l1]
y = df[["prognosis"]]
np.ravel(y)

array([ 0,  0,  0, ..., 38, 39, 40])

## Decision Tree Training

In [18]:
X = df[l1] #features
y = df[["prognosis"]] #targetvariable
print(y.head())
print()
print (X.head())

   prognosis
0          0
1          0
2          0
3          0
4          0

   back_pain  constipation  abdominal_pain  diarrhoea  mild_fever  \
0          0             0               0          0           0   
1          0             0               0          0           0   
2          0             0               0          0           0   
3          0             0               0          0           0   
4          0             0               0          0           0   

   yellow_urine  yellowing_of_eyes  acute_liver_failure  fluid_overload  \
0             0                  0                    0               0   
1             0                  0                    0               0   
2             0                  0                    0               0   
3             0                  0                    0               0   
4             0                  0                    0               0   

   swelling_of_stomach  ...  pus_filled_pimples  blackh

## Training Models

In [31]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import pickle

In [22]:
print(X.shape)
print(y.shape)

(4920, 95)
(4920, 1)


In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [24]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3296, 95)
(3296, 1)
(1624, 95)
(1624, 1)


## Decision Tree

In [ ]:
# Function to train the Decision Tree model
def train_decision_tree(x, y):
  clf = tree.DecisionTreeClassifier(criterion="gini")
  clf.fit(x, y)
  return clf

dt = train_decision_tree(X, y)

In [ ]:
y_pred= dt.predict(X_test)
print("Decision Tree")
print("Accuracy")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Decision Tree
Accuracy
0.9353448275862069
1519
Confusion matrix
[[40  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 43  0  0]
 [ 0  0  0 ...  0 45  0]
 [ 0  0  0 ...  0  0 31]]


In [ ]:
filename_sav = "DT_model.sav"
pickle.dump(dt, open(filename_sav, "wb"))
filename_pkl = "DT_model.pkl"
pickle.dump(dt, open(filename_pkl, "wb"))

## KNN model

In [32]:
from sklearn.neighbors import KNeighborsClassifier

# Function to train the KNN model
def train_knn(x, y, n_neighbors=5):
    clf = KNeighborsClassifier(n_neighbors=n_neighbors)
    clf.fit(x, y)
    return clf

knn = train_knn(X, y)

/home/roger22/.local/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [33]:
y_pred= knn.predict(X_test)
print("Decision Tree")
print("Accuracy")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Decision Tree
Accuracy
0.9396551724137931
1526
Confusion matrix
[[40  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 43  0  0]
 [ 0  0  0 ...  0 45  0]
 [ 0  0  0 ...  0  0 31]]


In [ ]:
filename_sav = "/artifacts/knn_model.sav"
pickle.dump(dt, open(filename_sav, "wb"))
filename_pkl = "/artifacts/knn_model.pkl"
pickle.dump(dt, open(filename_pkl, "wb"))

## Naive Bayes model

In [ ]:
y_pred= knn.predict(X_test)
print("Decision Tree")
print("Accuracy")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

In [ ]:
filename_sav = "/artifacts/NBayes.sav"
pickle.dump(dt, open(filename_sav, "wb"))
filename_pkl = "/artifacts/NBayes.pkl"
pickle.dump(dt, open(filename_pkl, "wb"))

## Random Forest model

In [34]:
from sklearn.ensemble import RandomForestClassifier

# Function to train the Random Forest model
def train_random_forest(x, y, n_estimators=100):
    clf = RandomForestClassifier(n_estimators=n_estimators, criterion="gini", random_state=42)
    clf.fit(x, y)
    return clf

rf = train_random_forest(X, y)

/tmp/ipykernel_27800/1953162834.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(x, y)


In [35]:
y_pred= rf.predict(X_test)
print("Decision Tree")
print("Accuracy")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Decision Tree
Accuracy
0.9365763546798029
1521
Confusion matrix
[[40  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ... 43  0  0]
 [ 0  0  0 ...  0 45  0]
 [ 0  0  0 ...  0  0 31]]


In [ ]:
filename_sav = "/artifacts/Rforest.sav"
pickle.dump(dt, open(filename_sav, "wb"))
filename_pkl = "/artifacts/Rforest.pkl"
pickle.dump(dt, open(filename_pkl, "wb"))

## SVM Model 

In [ ]:
y_pred= knn.predict(X_test)
print("Decision Tree")
print("Accuracy")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

In [ ]:
filename_sav = "/artifacts/svm_model.sav"
pickle.dump(dt, open(filename_sav, "wb"))
filename_pkl = "/artifacts/svm_model.pkl"
pickle.dump(dt, open(filename_pkl, "wb"))

## Sample Prediction Code on any model

In [110]:
# Main execution
#clf = train_decision_tree(X, y)

# Taking input from the user
symptoms = []

# Mandatory input for the first two symptoms
for i in range(1, 3):  # Loop for the first two mandatory symptoms
    symptom = input(f"Enter {i} symptom (mandatory): ")
    symptoms.append(symptom)

# Optional input for the next three symptoms
for i in range(3, 6):  # Loop for the next three optional symptoms
    symptom = input(f"Enter {i} symptom (optional, press Enter to skip): ")
    if symptom:  # Only append if the user has entered a symptom
        symptoms.append(symptom)

print(symptoms)
print(type(symptoms))
sy = pd.DataFrame(symptoms)
print(sy)
print(type(sy))
# Predicting the disease
predicted_disease = predict_disease(clf, symptoms)
print(f"The predicted disease is: {predicted_disease}")

Enter 1 symptom (mandatory): itching
Enter 2 symptom (mandatory): skin_rash
Enter 3 symptom (optional, press Enter to skip): nodal_skin_eruptions
Enter 4 symptom (optional, press Enter to skip): 
Enter 5 symptom (optional, press Enter to skip): 
['itching', 'skin_rash', 'nodal_skin_eruptions']
<class 'list'>
                      0
0               itching
1             skin_rash
2  nodal_skin_eruptions
<class 'pandas.core.frame.DataFrame'>
The predicted disease is: Drug Reaction


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
